### PR TITLE
Adding Google Tag Manager

### PR DESCRIPTION
**Pull request by alexbfree**

### CODE REVIEW

**Comment by aweiksnar** [comment]
It looks like single page apps might require additional configuration, unless things have changed since this was published: 
http://dan-russell.com/2013/07/google-tag-manager-for-single-page-applications/

**Comment by alexbfree** [comment]
@aweiksnar  It's OK, we already have this working on Serengeti, which is pretty much the same code. This checkin just handles basic page loads etc (the stuff standard analytics.js already does). We would then need to add custom events for interactions, as we have on Serengeti, but that's not part of this checkin, that would be something to do later, building upon this.

**Comment by aweiksnar** [comment]
Okay great, I'll merge/deploy this today

**Comment by aweiksnar** [comment]
All set!
Deployed to production now

**Pull request merged**
